@url = http://localhost:3033 

### simple users READ 
GET {{url}}/simpleUsers
content-type: application/json

### simple users CREATE 
POST {{url}}/simpleUsers/create
content-type: application/json

{
	"firstName": "Andre",
	"lastName": "Hackerkrug"
}

### simple users DELETE 
POST {{url}}/simpleUsers/delete/619d8061e3c04dfe88c85936
content-type: application/json